__fish_apple_touchbar_bind_key_custom 1 '👈' 'prevd' '-s'
__fish_apple_touchbar_bind_key_custom 2 '🗄 jump' 'cdh' '-s'
__fish_apple_touchbar_bind_key_custom 3 '📒 list' 'ls -l' '-s'
__fish_apple_touchbar_bind_key_custom 4 '𖡻 du' 'dust' '-s'
__fish_apple_touchbar_bind_key_custom 5 '🚦 top' 'sudo htop' '-s'
__fish_apple_touchbar_bind_key_custom 6 '📊 btm' 'btm' '-s'
__fish_apple_touchbar_bind_key_custom 7 '╂ split' 'osascript -e "tell application \"System Events\" to key code 2 using command down"' '-s'
__fish_apple_touchbar_bind_key_custom 8 '┿ split' 'osascript -e "tell application \"System Events\" to key code 2 using {shift down, command down}"' '-s'
__fish_apple_touchbar_bind_key_custom 9 '📂 open' 'open .' '-s'
__fish_apple_touchbar_bind_key_custom 10 '👨‍💻 code lines' 'tokei' '-s'

