[blame]
    coloring = highlightRecent
    date = human
[color]
    ui = auto
[color "blame"]
    highlightRecent = 238, 19 month ago, 239, 18 month ago, 240, 17 month ago, 241, 16 month ago, 242, 15 month ago, 243, 14 month ago, 244, 13 month ago, 245, 12 month ago, 246, 11 month ago, 247, 10 month ago, 248, 9 month ago, 249, 8 month ago, 250, 7 month ago, 251, 6 month ago, 252, 5 month ago, 253, 4 month ago, 254, 3 month ago, 231, 2 month ago, 230, 1 month ago, 229, 3 weeks ago, 228, 2 weeks ago, 227, 1 week ago, 226
[color "branch"]
    current = "#d8712c bold"
    local = "#d8712c"
    remote = green
[color "decorate"]
    head = "#959494"
    branch = "#d8712c"
[color "diff"]
    commit = "#d8712c"
    frag = magenta bold
    meta = "#d8712c bold"
    new = green bold
    old = red bold
    whitespace = red reverse
    remote = "#959494"
[color "status"]
    added = "#d8712c bold"
    changed = "#b65d26"
    untracked = "#BF5B30 bold"
    deleted = "#BF5B30 normal"
    header = "#959494"
[delta]
    features = side-by-side line-numbers decorations
    whitespace-error-style = 22 reverse
[delta "decorations"]
    commit-decoration-style = "#959494" box ul
    file-style = bold yellow ul
    file-decoration-style = none
[interactive]
    diffFilter = delta --color-only
[log]
	decorate = auto

